/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvisorIndexRouteImport } from './routes/advisor/index'
import { Route as ChatClientIdRouteImport } from './routes/chat.$clientId'
import { Route as AdvisorClientsClientIdRouteImport } from './routes/advisor/clients.$clientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorIndexRoute = AdvisorIndexRouteImport.update({
  id: '/advisor/',
  path: '/advisor/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatClientIdRoute = ChatClientIdRouteImport.update({
  id: '/chat/$clientId',
  path: '/chat/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorClientsClientIdRoute = AdvisorClientsClientIdRouteImport.update({
  id: '/advisor/clients/$clientId',
  path: '/advisor/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat/$clientId': typeof ChatClientIdRoute
  '/advisor/': typeof AdvisorIndexRoute
  '/advisor/clients/$clientId': typeof AdvisorClientsClientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat/$clientId': typeof ChatClientIdRoute
  '/advisor': typeof AdvisorIndexRoute
  '/advisor/clients/$clientId': typeof AdvisorClientsClientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat/$clientId': typeof ChatClientIdRoute
  '/advisor/': typeof AdvisorIndexRoute
  '/advisor/clients/$clientId': typeof AdvisorClientsClientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/chat/$clientId' | '/advisor/' | '/advisor/clients/$clientId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chat/$clientId' | '/advisor' | '/advisor/clients/$clientId'
  id:
    | '__root__'
    | '/'
    | '/chat/$clientId'
    | '/advisor/'
    | '/advisor/clients/$clientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatClientIdRoute: typeof ChatClientIdRoute
  AdvisorIndexRoute: typeof AdvisorIndexRoute
  AdvisorClientsClientIdRoute: typeof AdvisorClientsClientIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor/': {
      id: '/advisor/'
      path: '/advisor'
      fullPath: '/advisor/'
      preLoaderRoute: typeof AdvisorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$clientId': {
      id: '/chat/$clientId'
      path: '/chat/$clientId'
      fullPath: '/chat/$clientId'
      preLoaderRoute: typeof ChatClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor/clients/$clientId': {
      id: '/advisor/clients/$clientId'
      path: '/advisor/clients/$clientId'
      fullPath: '/advisor/clients/$clientId'
      preLoaderRoute: typeof AdvisorClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatClientIdRoute: ChatClientIdRoute,
  AdvisorIndexRoute: AdvisorIndexRoute,
  AdvisorClientsClientIdRoute: AdvisorClientsClientIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
